name: Build Marketplace JSON

on:
  push:
    branches:
      - main # Or 'master'
    paths:
      - 'published_decks/**'
      - '.github/workflows/build_marketplace.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build marketplace.json
        id: build
        run: |
          DECKS_DIR="published_decks"
          OUTPUT_FILE="marketplace.json"
          
          # Use jq to safely combine all .json files in the directory into a single array
          # The -s (--slurp) flag reads all JSON objects into a single array
          if [ -d "$DECKS_DIR" ] && [ -n "$(ls -A $DECKS_DIR/*.json 2>/dev/null)" ]; then
            jq -s '.' $DECKS_DIR/*.json > $OUTPUT_FILE
            echo "Marketplace file built successfully from $(ls -1 $DECKS_DIR/*.json | wc -l) decks."
          else
            echo "[]" > $OUTPUT_FILE
            echo "No decks in $DECKS_DIR. Created empty marketplace file."
          fi
          
          echo "--- Generated marketplace.json content ---"
          cat $OUTPUT_FILE
          echo "----------------------------------------"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'Marketplace Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git add marketplace.json
          if ! git diff --staged --quiet; then
            git commit -m "Automated marketplace build"
            git push
          else
            echo "No changes to marketplace.json. Nothing to commit."
          fi
